# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='alt_names',
        ),
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
